version: "3.8"
services:
    frontend:
        container_name: frontend
        image: jaydenlsf/spring-petclinic-angular
        build: ./frontend
        ports:
        - target: 8080
          published: 8080
          protocol: tcp
    backend:
        container_name: backend
        image: springcommunity/spring-petclinic-rest
        ports:
        - target: 9966
          published: 9966
          protocol: tcp
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
        - target: 80
          published: 80
          protocol: tcp
        volumes:
        - type: bind
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf