pipeline {
    agent any
    environment {
        docker_credentials = credentials('docker_credentials')
    }
    stages{
        stage('Build'){
            steps{
                sh "bash jenkins/scripts/build.sh"
            }
        }
        stage('Test'){
            steps{
                sh "bash jenkins/scripts/test.sh"
            }
        }
        stage('Deploy') {
            steps {
                sh "bash jenkins/scripts/deploy.sh"
            }
        }
    }
}